#!/usr/bin/env bash
# plugin-scaffold.sh — deterministic scaffolding and feature generation for
# standalone WP Pro Max plugins. Reads/writes wp-plugin.json in CWD.
#
# Subcommands:
#   new                     Scaffold the plugin skeleton.
#   add <feature> [name]    Add a feature generator (cpt|taxonomy|settings|rest|shortcode|block).

set -euo pipefail

# Resolve paths -------------------------------------------------------------
if [ -n "${BASH_VERSION:-}" ]; then
	_SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
elif [ -n "${ZSH_VERSION:-}" ]; then
	_SCRIPT_DIR="$(dirname "${(%):-%x}")"
fi
_CLAUDE_PLUGIN_ROOT="${_SCRIPT_DIR}/.."
_REFERENCE_DIR="${_CLAUDE_PLUGIN_ROOT}/skills/wp-plugin-dev/references"

# Load manifest helpers ------------------------------------------------------
export WP_PLUGIN_FILE="${WP_PLUGIN_FILE:-./wp-plugin.json}"
# shellcheck source=plugin-manifest-lib.sh
source "${_SCRIPT_DIR}/plugin-manifest-lib.sh"

# Manifest-derived globals ---------------------------------------------------
SLUG=''
NAMESPACE=''
TEXTDOMAIN=''
NAME=''
VERSION=''
CONST_PREFIX=''

_load_manifest() {
	if [ ! -f "$WP_PLUGIN_FILE" ]; then
		echo "plugin-scaffold: $WP_PLUGIN_FILE not found" >&2
		exit 1
	fi
	SLUG="$(wpplugin_get '.plugin.slug')"
	NAMESPACE="$(wpplugin_get '.plugin.namespace')"
	TEXTDOMAIN="$(wpplugin_get '.plugin.textDomain')"
	NAME="$(wpplugin_get '.plugin.name')"
	VERSION="$(wpplugin_get '.plugin.version // "0.1.0"')"
	CONST_PREFIX="$(printf '%s' "$SLUG" | tr '[:lower:]-' '[:upper:]_')"
}

# Utility --------------------------------------------------------------------
_require_jq() {
	command -v jq >/dev/null 2>&1 || { echo "plugin-scaffold: jq required" >&2; return 1; }
}

# Extract a fenced code block that follows a `<!-- file: MARKER -->` comment.
_extract_block() {
	local md="${1:?md file}" marker="${2:?marker}"
	if [ ! -f "$md" ]; then
		echo "plugin-scaffold: reference missing: $md" >&2
		return 1
	fi
	awk -v m="$marker" '
		$0 ~ "^<!-- file: " m " -->$" { found = 1; next }
		found && /^```/ {
			if (inblock) { exit }
			inblock = 1
			next
		}
		found && inblock { print }
	' "$md"
}

# Tokenize a template on common manifest tokens.
_tokenize() {
	sed \
		-e "s|__SLUG__|$SLUG|g" \
		-e "s|__NAMESPACE__|$NAMESPACE|g" \
		-e "s|__TEXTDOMAIN__|$TEXTDOMAIN|g" \
		-e "s|__NAME__|$NAME|g" \
		-e "s|__VERSION__|$VERSION|g" \
		-e "s|__CONST_PREFIX__|$CONST_PREFIX|g" \
		-e "s|__AUTHOR__|Netko Solution|g" \
		-e "s|__DESCRIPTION__|Generated by WP Pro Max|g"
}

# Write a file only if it does not already exist.
_write_if_missing() {
	local file="${1:?file}" content="${2:-}"
	if [ -f "$file" ]; then
		echo "plugin-scaffold: skip existing $file" >&2
		return 0
	fi
	mkdir -p "$(dirname "$file")"
	printf '%s\n' "$content" > "$file"
	echo "plugin-scaffold: wrote $file" >&2
}

# Insert code immediately before the registrar marker.
_insert_at_marker() {
	local file="${1:?file}" insert="${2:?insert}"
	local marker='/* wp-plugin-dev:registrar */'
	if ! grep -q -F "$marker" "$file"; then
		echo "plugin-scaffold: registrar marker missing in $file" >&2
		return 1
	fi
	perl - "$marker" "$insert" "$file" <<'EOF_PERL'
		my $marker = $ARGV[0];
		my $insert = $ARGV[1];
		my $file   = $ARGV[2];
		open( my $fh, "<", $file ) or die "cannot read $file: $!";
		local $/;
		my $content = <$fh>;
		close $fh;
		my $pos = index( $content, $marker );
		die "marker not found" if $pos < 0;

		# Walk back to the start of the line and capture indentation.
		my $line_start = $pos;
		while ( $line_start > 0 && substr( $content, $line_start - 1, 1 ) ne "\n" ) {
			$line_start--;
		}
		my $indent = '';
		my $p = $line_start;
		while ( $p < $pos && substr( $content, $p, 1 ) =~ /^[ \t]$/ ) {
			$indent .= substr( $content, $p, 1 );
			$p++;
		}

		substr( $content, $line_start, 0 ) = $indent . $insert . "\n";
		open( $fh, ">", $file ) or die "cannot write $file: $!";
		print $fh $content;
		close $fh;
EOF_PERL
	grep -q -F "$marker" "$file"
}

# Append a feature record to wp-plugin.json features[] (last step of add).
_record_feature() {
	local type="${1:?type}" name="${2:-}" rest_exposed="${3:-false}"
	_require_jq
	local entry="{\"type\":\"$type\""
	[ -n "$name" ] && entry="$entry,\"name\":\"$name\""
	[ "$type" = "cpt" ] && entry="$entry,\"restExposed\":$rest_exposed"
	entry="$entry}"
	local tmp
	tmp="$(mktemp)"
	jq ".features = ((.features // []) + [$entry])" "$WP_PLUGIN_FILE" > "$tmp" && mv "$tmp" "$WP_PLUGIN_FILE"
}

# Helper: check if a feature type is already recorded.
_has_feature() {
	local type="${1:?type}"
	_require_jq
	[ "$(jq --arg t "$type" '(.features // [])[] | select(.type == $t) | .type' "$WP_PLUGIN_FILE" | head -n1)" = "$type" ]
}

# Convert CamelCase to snake_case (e.g. ItemCategory -> item_category).
_to_snake() {
	printf '%s' "$1" | perl -pe 's/([A-Z])/_\l$1/g; s/^_//'
}

# Convert CamelCase to kebab-case (e.g. ItemCategory -> item-category).
_to_kebab() {
	printf '%s' "$1" | perl -pe 's/([A-Z])/-\l$1/g; s/^-//'
}

# ----------------------------------------------------------------------------
# new — scaffold the plugin skeleton
# ----------------------------------------------------------------------------
cmd_new() {
	_load_manifest

	mkdir -p inc src languages

	local bootstrap uninstall autoloader plugin_php gitignore readme
	bootstrap="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" bootstrap.php | _tokenize)"
	uninstall="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" uninstall.php | _tokenize)"
	autoloader="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" inc/autoload.php | _tokenize)"
	plugin_php="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" src/Plugin.php | _tokenize)"
	gitignore="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" .gitignore)"
	readme="$(_extract_block "${_REFERENCE_DIR}/plugin-architecture.md" readme.txt | _tokenize)"

	_write_if_missing "${SLUG}.php" "$bootstrap"
	_write_if_missing uninstall.php "$uninstall"
	_write_if_missing inc/autoload.php "$autoloader"
	_write_if_missing src/Plugin.php "$plugin_php"
	_write_if_missing .gitignore "$gitignore"
	_write_if_missing readme.txt "$readme"

	wpplugin_progress scaffold done "created skeleton"
	echo "plugin-scaffold: plugin skeleton ready in $(pwd)" >&2
}

# ----------------------------------------------------------------------------
# add — feature generators
# ----------------------------------------------------------------------------
FEATURE_TYPE=''
FEATURE_NAME=''
FEATURE_CLASS=''
FEATURE_SLUG=''
FEATURE_SLUG_KEBAB=''
FEATURE_REST_BASE=''
FEATURE_OPTION=''

_set_feature_defaults() {
	case "$FEATURE_TYPE" in
		cpt)       FEATURE_NAME="${1:-Item}" ;;
		taxonomy)  FEATURE_NAME="${1:-ItemCategory}" ;;
		settings)  FEATURE_NAME='' ;;
		rest)      FEATURE_NAME="${1:-Item}" ;;
		shortcode) FEATURE_NAME="${1:-Item}" ;;
		block)     FEATURE_NAME="${1:-Hero}" ;;
		*) echo "plugin-scaffold: unknown feature type '$FEATURE_TYPE'" >&2; exit 2 ;;
	esac
}

# Load feature-specific tokens.
_load_feature_vars() {
	local custom_name="${1:-}"
	_set_feature_defaults "$custom_name"
	case "$FEATURE_TYPE" in
		cpt)
			FEATURE_CLASS="${FEATURE_NAME}PostType"
			FEATURE_SLUG="$(_to_snake "$FEATURE_NAME")"
			FEATURE_REST_BASE="${FEATURE_SLUG}s"
			FEATURE_OPTION="${CONST_PREFIX}_$(printf '%s' "$FEATURE_SLUG" | tr '[:lower:]' '[:upper:]')_SETTINGS"
			FEATURE_SHOW_IN_REST='false'
			;;
		taxonomy)
			FEATURE_CLASS="${FEATURE_NAME}Taxonomy"
			FEATURE_SLUG="$(_to_snake "$FEATURE_NAME")"
			FEATURE_REST_BASE="${FEATURE_SLUG}s"
			FEATURE_OBJECT_TYPE='item'
			FEATURE_OPTION=""
			;;
		settings)
			FEATURE_CLASS='SettingsPage'
			FEATURE_SLUG="${CONST_PREFIX}_settings"
			FEATURE_OPTION="${CONST_PREFIX}_settings"
			;;
		rest)
			FEATURE_CLASS="${FEATURE_NAME}Controller"
			FEATURE_SLUG="$(_to_snake "$FEATURE_NAME")"
			FEATURE_REST_BASE="${FEATURE_SLUG}s"
			FEATURE_OPTION=""
			;;
		shortcode)
			FEATURE_CLASS="${FEATURE_NAME}Shortcode"
			FEATURE_SLUG="$(_to_snake "$FEATURE_NAME")"
			FEATURE_SLUG_KEBAB="$(_to_kebab "$FEATURE_NAME")"
			FEATURE_OPTION=""
			;;
		block)
			FEATURE_CLASS="${FEATURE_NAME}Block"
			FEATURE_SLUG="$(_to_snake "$FEATURE_NAME")"
			FEATURE_SLUG_KEBAB="$(_to_kebab "$FEATURE_NAME")"
			FEATURE_OPTION=""
			;;
	esac
}

# Tokenize a feature/block template on both common and feature-specific tokens.
_tokenize_feature() {
	_tokenize \
		| sed \
			-e "s|__FEATURE_NAME__|$FEATURE_NAME|g" \
			-e "s|__FEATURE_CLASS__|$FEATURE_CLASS|g" \
			-e "s|__FEATURE_SLUG__|$FEATURE_SLUG|g" \
			-e "s|__FEATURE_SLUG_KEBAB__|$FEATURE_SLUG_KEBAB|g" \
			-e "s|__FEATURE_REST_BASE__|$FEATURE_REST_BASE|g" \
			-e "s|__FEATURE_OPTION__|$FEATURE_OPTION|g" \
			-e "s|__FEATURE_OBJECT_TYPE__|${FEATURE_OBJECT_TYPE:-item}|g" \
			-e "s|__SHOW_IN_REST__|${FEATURE_SHOW_IN_REST:-false}|g"
}

# Insert the registration line for a feature class into src/Plugin.php.
_register_feature_class() {
	local class_path="${1:?class path}"
	local tab=$'\t'
	local snippet="${tab}${tab}( new \\${NAMESPACE}\\${class_path}() )->register();"
	_insert_at_marker src/Plugin.php "$snippet"
}

# Feature: Custom Post Type --------------------------------------------------
_add_cpt() {
	local rest_exposed="false"
	[ "${2:-}" = "true" ] && rest_exposed="true"
	FEATURE_SHOW_IN_REST="$rest_exposed"

	local body
	body="$(_extract_block "${_REFERENCE_DIR}/feature-generators.md" PostTypes/ItemPostType.php | _tokenize_feature)"
	_write_if_missing "src/PostTypes/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "PostTypes\\${FEATURE_CLASS}"
	_record_feature cpt "$FEATURE_NAME" "$rest_exposed"
}

# Feature: Taxonomy ----------------------------------------------------------
_add_taxonomy() {
	local body
	body="$(_extract_block "${_REFERENCE_DIR}/feature-generators.md" PostTypes/ItemTaxonomy.php | _tokenize_feature)"
	_write_if_missing "src/PostTypes/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "PostTypes\\${FEATURE_CLASS}"
	_record_feature taxonomy "$FEATURE_NAME"
}

# Feature: Settings Page -----------------------------------------------------
_add_settings() {
	local body
	body="$(_extract_block "${_REFERENCE_DIR}/feature-generators.md" Admin/SettingsPage.php | _tokenize_feature)"
	_write_if_missing "src/Admin/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "Admin\\${FEATURE_CLASS}"
	_record_feature settings
}

# Feature: REST Controller ---------------------------------------------------
_add_rest() {
	local body
	body="$(_extract_block "${_REFERENCE_DIR}/feature-generators.md" Rest/ItemsController.php | _tokenize_feature)"
	_write_if_missing "src/Rest/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "Rest\\${FEATURE_CLASS}"
	_record_feature rest "$FEATURE_NAME"
}

# Feature: Shortcode ---------------------------------------------------------
_add_shortcode() {
	local body
	body="$(_extract_block "${_REFERENCE_DIR}/feature-generators.md" Shortcodes/ItemShortcode.php | _tokenize_feature)"
	_write_if_missing "src/Shortcodes/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "Shortcodes\\${FEATURE_CLASS}"
	_record_feature shortcode "$FEATURE_NAME"
}

# Feature: Block -------------------------------------------------------------
_add_block() {
	local lower_name
	lower_name="$(printf '%s' "$FEATURE_NAME" | tr '[:upper:]' '[:lower:]')"

	# PHP class.
	local body
	body="$(_extract_block "${_REFERENCE_DIR}/block-build.md" Blocks/HeroBlock.php | _tokenize_feature)"
	_write_if_missing "src/Blocks/${FEATURE_CLASS}.php" "$body"
	_register_feature_class "Blocks\\${FEATURE_CLASS}"

	# block.json, JS, SCSS.
	mkdir -p "blocks/${lower_name}/src"
	_write_if_missing "blocks/${lower_name}/block.json" "$(_extract_block "${_REFERENCE_DIR}/block-build.md" blocks/hero/block.json | _tokenize_feature)"
	_write_if_missing "blocks/${lower_name}/src/index.js" "$(_extract_block "${_REFERENCE_DIR}/block-build.md" blocks/hero/src/index.js | _tokenize_feature)"
	_write_if_missing "blocks/${lower_name}/src/edit.js" "$(_extract_block "${_REFERENCE_DIR}/block-build.md" blocks/hero/src/edit.js | _tokenize_feature)"
	_write_if_missing "blocks/${lower_name}/src/style.scss" "$(_extract_block "${_REFERENCE_DIR}/block-build.md" blocks/hero/src/style.scss | _tokenize_feature)"
	_write_if_missing "blocks/${lower_name}/src/editor.scss" "$(_extract_block "${_REFERENCE_DIR}/block-build.md" blocks/hero/src/editor.scss | _tokenize_feature)"

	# package.json only on first block.
	if [ ! -f package.json ]; then
		_write_if_missing package.json "$(_extract_block "${_REFERENCE_DIR}/block-build.md" package.json | _tokenize_feature)"
	fi

	# Flip tooling flag.
	wpplugin_set '.tooling.blockBuild' 'true'

	_record_feature block "$FEATURE_NAME"
}

# Main add dispatcher --------------------------------------------------------
cmd_add() {
	_load_manifest

	FEATURE_TYPE="${1:?feature type required}"
	local custom_name="${2:-}"

	if _has_feature "$FEATURE_TYPE"; then
		echo "plugin-scaffold: feature '$FEATURE_TYPE' already recorded in $WP_PLUGIN_FILE; skipping" >&2
		exit 0
	fi

	_load_feature_vars "$custom_name"

	case "$FEATURE_TYPE" in
		cpt)       _add_cpt "$custom_name" ;;
		taxonomy)  _add_taxonomy "$custom_name" ;;
		settings)  _add_settings ;;
		rest)      _add_rest "$custom_name" ;;
		shortcode) _add_shortcode "$custom_name" ;;
		block)     _add_block "$custom_name" ;;
		*)         echo "plugin-scaffold: unknown feature '$FEATURE_TYPE'" >&2; exit 2 ;;
	esac

	echo "plugin-scaffold: added $FEATURE_TYPE${FEATURE_NAME:+ ($FEATURE_NAME)}" >&2
}

# ----------------------------------------------------------------------------
# Entrypoint
# ----------------------------------------------------------------------------
cmd="${1:-}"
case "$cmd" in
	new) cmd_new ;;
	add) shift; cmd_add "$@" ;;
	*) echo "usage: plugin-scaffold.sh {new|add <feature> [name]}" >&2; exit 2 ;;
esac
